task: CircuitEnvTest-v3
reward_threshold: 100
seed: 1996
buffer_size: 20000
lr: 0.0001
gamma: 0.99
epoch: 4000
step_per_epoch: 20000
step_per_collect: 20000
repeat_per_collect: 200
batch_size: 640
#hidden_sizes: [ 128,256,512,1024,512,512]
hidden_sizes: [ 128,256,256,128]
training_num: 20
test_num: 5
logdir: log
render: 0.0
device: cuda

# ppo special
vf_coef: 0.5
ent_coef: 0.0
eps_clip: 0.2
max_grad_norm: 0.5
gae_lambda: 0.95
rew_norm: 0
norm_adv: 0
recompute_adv: 0
dual_clip: null
value_clip: 0
actor_lr: 0.0001
critic_lr: 0.0001
tau: 0.005
exploration_noise: 0.4
max_epoch: 10000
n_step: 1024

#cricuit special
#circuit_name: simple_demo.qasm
circuit_name: qftentangled_indep_qiskit_10.qasm


#rainbowDQN
num_atoms : 51
v_min: -10.0
v_max: 10.0
noisy_std: 0.1
target_update_freq: 32
prioritized_replay: True
beta_final: 1.0
beta: 0.4
resume: false
alpha: 0.6
update_per_step: 0.125
eps_test: 0.05
eps_train: 0.1